### ISSUE TITLE
Feature parity with StravaKit for iOS

### ISSUE THREAD

**Issue by brennanMKE** [loisaidasam/strava-authenticator-android#1]
Perhaps this library and StravaKit can work toward providing similar functionality so they can be used to support similar apps for Android and iOS. So far StravaKit handles OAuth authorization. It also provides support for the endpoints in the public scope. Later the private and write scopes will be supported.

Is there anything that could be done to ensure both apps support the same features needed by mobile apps?

**Comment by loisaidasam** [comment]
Hi @brennanMKE 

While I applaud your effort, this library is meant just for the Authentication piece.

There are a handful of other Strava Java/Android client libraries out there that would be better potential partners for StravaKit:

- [https://github.com/dustedrob/JStrava](https://github.com/dustedrob/JStrava)
- [http://danshannon.github.io/javastravav3api/](http://danshannon.github.io/javastravav3api/)
- [https://github.com/tiberiu-biking/scribejava-strava](https://github.com/tiberiu-biking/scribejava-strava)
- [https://github.com/SweetzpotAS/StravaZpot-Android](https://github.com/SweetzpotAS/StravaZpot-Android)

Gonna close this issue for now.
